# Generated by Django 2.2.16 on 2022-01-21 06:36

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='введите комментарий', max_length=20000, validators=[posts.validators.validate_not_empty], verbose_name='Tекст комментария'),
        ),
    ]
